/*
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol.ui.tests;

import br.ufes.inf.nemo.ontol.ui.internal.OntolActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class OntoLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OntolActivator.getInstance().getInjector("br.ufes.inf.nemo.ontol.OntoL");
	}

}
