/**
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol.validation;

import br.ufes.inf.nemo.ontol.validation.AbstractOntoLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OntoLValidator extends AbstractOntoLValidator {
}
