/**
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol.validation;

import br.ufes.inf.nemo.ontol.lib.OntoLLib;
import br.ufes.inf.nemo.ontol.model.EntityDeclaration;
import br.ufes.inf.nemo.ontol.model.FOClass;
import br.ufes.inf.nemo.ontol.model.GeneralizationSet;
import br.ufes.inf.nemo.ontol.model.HOClass;
import br.ufes.inf.nemo.ontol.model.ModelPackage;
import br.ufes.inf.nemo.ontol.model.OntoLClass;
import br.ufes.inf.nemo.ontol.model.Property;
import br.ufes.inf.nemo.ontol.model.PropertyAssignment;
import br.ufes.inf.nemo.ontol.util.OntoLUtils;
import br.ufes.inf.nemo.ontol.validation.AbstractOntoLValidator;
import br.ufes.inf.nemo.ontol.validation.LinguisticRules;
import br.ufes.inf.nemo.ontol.validation.MLTRules;
import br.ufes.inf.nemo.ontol.validation.UFORules;
import br.ufes.inf.nemo.ontol.validation.ValidationError;
import br.ufes.inf.nemo.ontol.validation.ValidationIssue;
import br.ufes.inf.nemo.ontol.validation.ValidationWarning;
import com.google.common.base.Objects;
import com.google.inject.Inject;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OntoLValidator extends AbstractOntoLValidator {
  @Inject
  @Extension
  private OntoLUtils _ontoLUtils;
  
  @Inject
  @Extension
  private OntoLLib _ontoLLib;
  
  @Inject
  @Extension
  private LinguisticRules _linguisticRules;
  
  @Inject
  @Extension
  private MLTRules _mLTRules;
  
  @Inject
  @Extension
  private UFORules _uFORules;
  
  public final static String INSTANTIATION_OF_DISJOINT_TYPES = "br.ufes.inf.nemo.ontol.InstantiationOfDisjointTypes";
  
  public final static String MISSING_COMPLETE_INSTANTIATION = "br.ufes.inf.nemo.ontol.MissingCompleteInstantiation";
  
  public final static String POWERTYPE_COMPLETE_SPECIALIZATION = "br.ufes.inf.nemo.ontol.PowertypeCompleteSpecialization";
  
  public final static String COMPLETE_CHARACTERIZATION_AND_COMPLETENESS = "br.ufes.inf.nemo.ontol.CompleteCharacterizationAndCompleteness";
  
  public final static String DISJOINT_CHARACTERIZATION_AND_DISJOINTNESS = "br.ufes.inf.nemo.ontol.DisjointCharacterizationAndDisjointness";
  
  public final static String MANDATORY_SPECIALIZATION_OF_ENDURANT = "br.ufes.inf.nemo.ontol.MandaorySpecializationOfEndurant";
  
  public final static String NONSORTAL_SPECIALIZING_SORTAL = "br.ufes.inf.nemo.ontol.NonSortalSpecializingSortal";
  
  public final static String RIGID_SPECIALIZING_ANTIRIGID = "br.ufes.inf.nemo.ontol.RigidSpecializingAntiRigid";
  
  public final static String SEMIRIGID_SPECIALIZING_ANTIRIGID = "br.ufes.inf.nemo.ontol.SemiRigidSpecializingAntiRigid";
  
  public final static String MULTIPLE_IDENTITIES = "br.ufes.inf.nemo.ontol.MultipleIdentities";
  
  public final static String MISSING_IDENTITY = "br.ufes.inf.nemo.ontol.MissingIdentity";
  
  public final static String NECESSARY_INSTANTIATION = "br.ufes.inf.nemo.ontol.NecessaryInstantiation";
  
  public final static String MISSING_SPECIALIZATION_TO_BASETYPE = "br.ufes.inf.nemo.ontol.MissingSpecializationToBasetype";
  
  public final static String UFO_A_MISSING_MUST_INSTANTIATION = "br.ufes.inf.nemo.ontol.ufo.a.MissingMustInstantiation";
  
  public final static String UFO_A_ILLEGAL_SORTAL_SPECIALIZATION = "br.ufes.inf.nemo.ontol.ufo.a.IllegalSortalSpecialization";
  
  public final static String UFO_A_ILLEGAL_RIGID_SPECIALIZATION = "br.ufes.inf.nemo.ontol.ufo.a.IllegalRigidSpecialization";
  
  public final static String NON_CONFORMANT_ASSIGNMENT = "br.ufes.inf.nemo.ontol.NonConformantAssigment";
  
  @Check(CheckType.FAST)
  public void fastChecksOnEntityDeclaration(final EntityDeclaration e) {
    boolean _isNameValid = this._linguisticRules.isNameValid(e);
    boolean _not = (!_isNameValid);
    if (_not) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Entity name must start with a capital letter.");
      EAttribute _entityDeclaration_Name = ModelPackage.eINSTANCE.getEntityDeclaration_Name();
      this.error(_builder.toString(), _entityDeclaration_Name, 
        LinguisticRules.INVALID_ENTITY_DECLARATION_NAME);
    }
    boolean _duplicatedEntityName = this._linguisticRules.duplicatedEntityName(e);
    if (_duplicatedEntityName) {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Entity name must be unique.");
      EAttribute _entityDeclaration_Name_1 = ModelPackage.eINSTANCE.getEntityDeclaration_Name();
      this.error(_builder_1.toString(), _entityDeclaration_Name_1, 
        LinguisticRules.DUPLICATED_ENTITY_NAME);
    }
  }
  
  @Check(CheckType.FAST)
  public void fastCheckOnClass(final OntoLClass c) {
    final Set<OntoLClass> ch = this._ontoLUtils.classHierarchy(c);
    boolean _isValidSpecialization = this._linguisticRules.isValidSpecialization(c);
    boolean _not = (!_isValidSpecialization);
    if (_not) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Invalid specialization.");
      EReference _ontoLClass_SuperClasses = ModelPackage.eINSTANCE.getOntoLClass_SuperClasses();
      this.error(_builder.toString(), _ontoLClass_SuperClasses, 
        LinguisticRules.INVALID_CLASS_SPECIALIZATION);
    }
    boolean _hasCyclicSpecialization = this._linguisticRules.hasCyclicSpecialization(c, ch);
    if (_hasCyclicSpecialization) {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Invalid cyclic specialization.");
      EReference _ontoLClass_SuperClasses_1 = ModelPackage.eINSTANCE.getOntoLClass_SuperClasses();
      this.error(_builder_1.toString(), _ontoLClass_SuperClasses_1, 
        LinguisticRules.CYCLIC_SPECIALIZATION);
    }
    boolean _hasValidBasetype = this._linguisticRules.hasValidBasetype(c);
    boolean _not_1 = (!_hasValidBasetype);
    if (_not_1) {
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Invalid basetype.");
      EReference _ontoLClass_Basetype = ModelPackage.eINSTANCE.getOntoLClass_Basetype();
      this.error(_builder_2.toString(), _ontoLClass_Basetype, 
        LinguisticRules.INVALID_BASETYPE);
    }
    boolean _hasValidPowertypeRelation = this._linguisticRules.hasValidPowertypeRelation(c);
    boolean _not_2 = (!_hasValidPowertypeRelation);
    if (_not_2) {
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("Invalid powertype relation.");
      EReference _ontoLClass_PowertypeOf = ModelPackage.eINSTANCE.getOntoLClass_PowertypeOf();
      this.error(_builder_3.toString(), _ontoLClass_PowertypeOf, 
        LinguisticRules.INVALID_POWERTYPE_RELATION);
    }
    boolean _hasValidSubordinators = this._linguisticRules.hasValidSubordinators(c);
    boolean _not_3 = (!_hasValidSubordinators);
    if (_not_3) {
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("Invalid subordinator.");
      EReference _ontoLClass_Subordinators = ModelPackage.eINSTANCE.getOntoLClass_Subordinators();
      this.error(_builder_4.toString(), _ontoLClass_Subordinators, 
        LinguisticRules.INVALID_SUBORDINATOR);
    }
  }
  
  @Check(CheckType.FAST)
  public void fastChecksOnHOClass(final HOClass ho) {
    boolean _minOrder = this._mLTRules.minOrder(ho);
    boolean _not = (!_minOrder);
    if (_not) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Order must be of ");
      _builder.append(MLTRules.MIN_ORDER, "");
      _builder.append(" or greater.");
      EAttribute _hOClass_Order = ModelPackage.eINSTANCE.getHOClass_Order();
      this.error(_builder.toString(), _hOClass_Order, 
        MLTRules.INVALID_HO_CLASS_ORDER);
    }
  }
  
  @Check(CheckType.FAST)
  public void fastChecksOnGeneralizationSet(final GeneralizationSet gs) {
    boolean _hasValidMembers = this._linguisticRules.hasValidMembers(gs);
    boolean _not = (!_hasValidMembers);
    if (_not) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("This generalization set has invalid members.");
      EAttribute _generalizationSet_Name = ModelPackage.eINSTANCE.getGeneralizationSet_Name();
      this.error(_builder.toString(), _generalizationSet_Name, 
        LinguisticRules.INVALID_GENERALIZATION_SET_MEMBERS);
    }
  }
  
  @Check(CheckType.FAST)
  public void fastChecksOnProperty(final Property p) {
    ValidationIssue _checkSubsettedMultiplicity = this._linguisticRules.checkSubsettedMultiplicity(p);
    if (_checkSubsettedMultiplicity!=null) {
      this.runIssue(_checkSubsettedMultiplicity);
    }
    ValidationIssue _checkRegularityAndContainer = this._linguisticRules.checkRegularityAndContainer(p);
    if (_checkRegularityAndContainer!=null) {
      this.runIssue(_checkRegularityAndContainer);
    }
  }
  
  @Check(CheckType.FAST)
  public void fastChecksOnPropertyAssignment(final PropertyAssignment pa) {
    ValidationIssue _checkMultiplicityAndAssignment = this._linguisticRules.checkMultiplicityAndAssignment(pa);
    if (_checkMultiplicityAndAssignment!=null) {
      this.runIssue(_checkMultiplicityAndAssignment);
    }
  }
  
  @Check(CheckType.NORMAL)
  public void normalChecksOnPropertyAssignment(final PropertyAssignment pa) {
    ValidationIssue _checkPropertyAssignmentType = this._linguisticRules.checkPropertyAssignmentType(pa);
    if (_checkPropertyAssignmentType!=null) {
      this.runIssue(_checkPropertyAssignmentType);
    }
  }
  
  @Check(CheckType.NORMAL)
  public void normalChecksOnEntity(final EntityDeclaration e) {
    final LinkedHashSet<OntoLClass> iof = this._ontoLUtils.getAllInstantiatedClasses(e);
    ValidationIssue _isInstanceOfDisjointClasses = this._linguisticRules.isInstanceOfDisjointClasses(e, iof);
    if (_isInstanceOfDisjointClasses!=null) {
      this.runIssue(_isInstanceOfDisjointClasses);
    }
    ValidationIssue _missingInstantiationByCompleteness = this._linguisticRules.missingInstantiationByCompleteness(e, iof);
    if (_missingInstantiationByCompleteness!=null) {
      this.runIssue(_missingInstantiationByCompleteness);
    }
  }
  
  @Check(CheckType.NORMAL)
  public void normalChecksOnClass(final OntoLClass c) {
    final Set<OntoLClass> ch = this._ontoLUtils.classHierarchy(c);
    final LinkedHashSet<OntoLClass> iof = this._ontoLUtils.getAllInstantiatedClasses(c);
    boolean _isMissingSpecializationThroughPowertype = this._mLTRules.isMissingSpecializationThroughPowertype(c, ch);
    if (_isMissingSpecializationThroughPowertype) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Missing specialization through powertype relation.");
      EReference _ontoLClass_SuperClasses = ModelPackage.eINSTANCE.getOntoLClass_SuperClasses();
      this.error(_builder.toString(), _ontoLClass_SuperClasses, MLTRules.MISSING_SPECIALIZATION_THROUGH_POWERTYPE);
    }
    boolean _obeysSubordination = this._linguisticRules.obeysSubordination(c, ch, iof);
    boolean _not = (!_obeysSubordination);
    if (_not) {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Missing specialization through subordination.");
      EReference _ontoLClass_SuperClasses_1 = ModelPackage.eINSTANCE.getOntoLClass_SuperClasses();
      this.error(_builder_1.toString(), _ontoLClass_SuperClasses_1, 
        LinguisticRules.MISSING_SPECIALIZATION_THROUGH_SUBODINATION);
    }
    boolean _hasSimpleSubordinationCycle = this._linguisticRules.hasSimpleSubordinationCycle(c);
    if (_hasSimpleSubordinationCycle) {
      StringConcatenation _builder_2 = new StringConcatenation();
      String _name = c.getName();
      _builder_2.append(_name, "");
      _builder_2.append(" is in a subordination cycle.");
      EReference _ontoLClass_Subordinators = ModelPackage.eINSTANCE.getOntoLClass_Subordinators();
      this.error(_builder_2.toString(), _ontoLClass_Subordinators, 
        LinguisticRules.SIMPLE_SUBORDINATION_CYCLE);
    }
    ValidationIssue _isSpecializingDisjointClasses = this._linguisticRules.isSpecializingDisjointClasses(c, ch);
    if (_isSpecializingDisjointClasses!=null) {
      this.runIssue(_isSpecializingDisjointClasses);
    }
    ValidationIssue _checkInstantiatedRegularities = this._linguisticRules.checkInstantiatedRegularities(c);
    if (_checkInstantiatedRegularities!=null) {
      this.runIssue(_checkInstantiatedRegularities);
    }
  }
  
  @Check(CheckType.EXPENSIVE)
  public void expensiveChecksOnFOClass(final FOClass c) {
    final Set<OntoLClass> ch = this._ontoLUtils.classHierarchy(((OntoLClass) c));
    final LinkedHashSet<OntoLClass> iof = this._ontoLUtils.getAllInstantiatedClasses(((OntoLClass) c));
    final OntoLClass endurant = this._ontoLLib.getUFOEndurant(c);
    final Set<OntoLClass> mustInstantiate = this._ontoLLib.getUFOMustInstantiateClasses(c);
    final OntoLClass mixinclass = this._ontoLLib.getLibClass(c, OntoLLib.UFO_MIXIN_CLASS);
    final OntoLClass rigidclass = this._ontoLLib.getLibClass(c, OntoLLib.UFO_RIGID_CLASS);
    final OntoLClass semirigidclass = this._ontoLLib.getLibClass(c, OntoLLib.UFO_SEMI_RIGID_CLASS);
    ValidationIssue _mustInstantiateUFOMetaproperties = this._uFORules.mustInstantiateUFOMetaproperties(c, ch, iof, endurant, mustInstantiate);
    if (_mustInstantiateUFOMetaproperties!=null) {
      this.runIssue(_mustInstantiateUFOMetaproperties);
    }
    ValidationIssue _checkSpecializationAndSortality = this._uFORules.checkSpecializationAndSortality(c, ch, iof, mixinclass);
    if (_checkSpecializationAndSortality!=null) {
      this.runIssue(_checkSpecializationAndSortality);
    }
    ValidationIssue _checkSpecializationAndRigidity = this._uFORules.checkSpecializationAndRigidity(c, ch, iof, rigidclass, semirigidclass);
    if (_checkSpecializationAndRigidity!=null) {
      this.runIssue(_checkSpecializationAndRigidity);
    }
  }
  
  private void _runIssue(final ValidationError issue) {
    final ValidationError it = issue;
    boolean _and = false;
    boolean _and_1 = false;
    boolean _and_2 = false;
    EObject _source = it.getSource();
    boolean _notEquals = (!Objects.equal(_source, null));
    if (!_notEquals) {
      _and_2 = false;
    } else {
      EStructuralFeature _feature = it.getFeature();
      boolean _notEquals_1 = (!Objects.equal(_feature, null));
      _and_2 = _notEquals_1;
    }
    if (!_and_2) {
      _and_1 = false;
    } else {
      int _index = it.getIndex();
      boolean _notEquals_2 = (_index != (-1));
      _and_1 = _notEquals_2;
    }
    if (!_and_1) {
      _and = false;
    } else {
      String _code = it.getCode();
      boolean _notEquals_3 = (!Objects.equal(_code, null));
      _and = _notEquals_3;
    }
    if (_and) {
      String _message = it.getMessage();
      EObject _source_1 = it.getSource();
      EStructuralFeature _feature_1 = it.getFeature();
      int _index_1 = it.getIndex();
      String _code_1 = it.getCode();
      String[] _issueData = it.getIssueData();
      this.error(_message, _source_1, _feature_1, _index_1, _code_1, _issueData);
    } else {
      boolean _and_3 = false;
      boolean _and_4 = false;
      EObject _source_2 = it.getSource();
      boolean _notEquals_4 = (!Objects.equal(_source_2, null));
      if (!_notEquals_4) {
        _and_4 = false;
      } else {
        EStructuralFeature _feature_2 = it.getFeature();
        boolean _notEquals_5 = (!Objects.equal(_feature_2, null));
        _and_4 = _notEquals_5;
      }
      if (!_and_4) {
        _and_3 = false;
      } else {
        String _code_2 = it.getCode();
        boolean _notEquals_6 = (!Objects.equal(_code_2, null));
        _and_3 = _notEquals_6;
      }
      if (_and_3) {
        String _message_1 = it.getMessage();
        EObject _source_3 = it.getSource();
        EStructuralFeature _feature_3 = it.getFeature();
        String _code_3 = it.getCode();
        String[] _issueData_1 = it.getIssueData();
        this.error(_message_1, _source_3, _feature_3, _code_3, _issueData_1);
      } else {
        boolean _and_5 = false;
        boolean _and_6 = false;
        EStructuralFeature _feature_4 = it.getFeature();
        boolean _notEquals_7 = (!Objects.equal(_feature_4, null));
        if (!_notEquals_7) {
          _and_6 = false;
        } else {
          int _index_2 = it.getIndex();
          boolean _notEquals_8 = (_index_2 != (-1));
          _and_6 = _notEquals_8;
        }
        if (!_and_6) {
          _and_5 = false;
        } else {
          String _code_4 = it.getCode();
          boolean _notEquals_9 = (!Objects.equal(_code_4, null));
          _and_5 = _notEquals_9;
        }
        if (_and_5) {
          String _message_2 = it.getMessage();
          EStructuralFeature _feature_5 = it.getFeature();
          int _index_3 = it.getIndex();
          String _code_5 = it.getCode();
          String[] _issueData_2 = it.getIssueData();
          this.error(_message_2, _feature_5, _index_3, _code_5, _issueData_2);
        } else {
          boolean _and_7 = false;
          boolean _and_8 = false;
          EObject _source_4 = it.getSource();
          boolean _notEquals_10 = (!Objects.equal(_source_4, null));
          if (!_notEquals_10) {
            _and_8 = false;
          } else {
            EStructuralFeature _feature_6 = it.getFeature();
            boolean _notEquals_11 = (!Objects.equal(_feature_6, null));
            _and_8 = _notEquals_11;
          }
          if (!_and_8) {
            _and_7 = false;
          } else {
            int _index_4 = it.getIndex();
            boolean _notEquals_12 = (_index_4 != (-1));
            _and_7 = _notEquals_12;
          }
          if (_and_7) {
            String _message_3 = it.getMessage();
            EObject _source_5 = it.getSource();
            EStructuralFeature _feature_7 = it.getFeature();
            int _index_5 = it.getIndex();
            this.error(_message_3, _source_5, _feature_7, _index_5);
          } else {
            boolean _and_9 = false;
            EObject _source_6 = it.getSource();
            boolean _notEquals_13 = (!Objects.equal(_source_6, null));
            if (!_notEquals_13) {
              _and_9 = false;
            } else {
              EStructuralFeature _feature_8 = it.getFeature();
              boolean _notEquals_14 = (!Objects.equal(_feature_8, null));
              _and_9 = _notEquals_14;
            }
            if (_and_9) {
              String _message_4 = it.getMessage();
              EObject _source_7 = it.getSource();
              EStructuralFeature _feature_9 = it.getFeature();
              this.error(_message_4, _source_7, _feature_9);
            } else {
              boolean _and_10 = false;
              EStructuralFeature _feature_10 = it.getFeature();
              boolean _notEquals_15 = (!Objects.equal(_feature_10, null));
              if (!_notEquals_15) {
                _and_10 = false;
              } else {
                String _code_6 = it.getCode();
                boolean _notEquals_16 = (!Objects.equal(_code_6, null));
                _and_10 = _notEquals_16;
              }
              if (_and_10) {
                String _message_5 = it.getMessage();
                EStructuralFeature _feature_11 = it.getFeature();
                String _code_7 = it.getCode();
                String[] _issueData_3 = it.getIssueData();
                this.error(_message_5, _feature_11, _code_7, _issueData_3);
              } else {
                boolean _and_11 = false;
                EStructuralFeature _feature_12 = it.getFeature();
                boolean _notEquals_17 = (!Objects.equal(_feature_12, null));
                if (!_notEquals_17) {
                  _and_11 = false;
                } else {
                  int _index_6 = it.getIndex();
                  boolean _notEquals_18 = (_index_6 != (-1));
                  _and_11 = _notEquals_18;
                }
                if (_and_11) {
                  String _message_6 = it.getMessage();
                  EStructuralFeature _feature_13 = it.getFeature();
                  int _index_7 = it.getIndex();
                  this.error(_message_6, _feature_13, _index_7);
                } else {
                  boolean _and_12 = false;
                  EObject _source_8 = it.getSource();
                  boolean _notEquals_19 = (!Objects.equal(_source_8, null));
                  if (!_notEquals_19) {
                    _and_12 = false;
                  } else {
                    EStructuralFeature _feature_14 = it.getFeature();
                    boolean _notEquals_20 = (!Objects.equal(_feature_14, null));
                    _and_12 = _notEquals_20;
                  }
                  if (_and_12) {
                    String _message_7 = it.getMessage();
                    EStructuralFeature _feature_15 = it.getFeature();
                    this.error(_message_7, _feature_15);
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  
  private void _runIssue(final ValidationWarning issue) {
    final ValidationWarning it = issue;
    boolean _and = false;
    boolean _and_1 = false;
    boolean _and_2 = false;
    EObject _source = it.getSource();
    boolean _notEquals = (!Objects.equal(_source, null));
    if (!_notEquals) {
      _and_2 = false;
    } else {
      EStructuralFeature _feature = it.getFeature();
      boolean _notEquals_1 = (!Objects.equal(_feature, null));
      _and_2 = _notEquals_1;
    }
    if (!_and_2) {
      _and_1 = false;
    } else {
      int _index = it.getIndex();
      boolean _notEquals_2 = (_index != (-1));
      _and_1 = _notEquals_2;
    }
    if (!_and_1) {
      _and = false;
    } else {
      String _code = it.getCode();
      boolean _notEquals_3 = (!Objects.equal(_code, null));
      _and = _notEquals_3;
    }
    if (_and) {
      String _message = it.getMessage();
      EObject _source_1 = it.getSource();
      EStructuralFeature _feature_1 = it.getFeature();
      int _index_1 = it.getIndex();
      String _code_1 = it.getCode();
      String[] _issueData = it.getIssueData();
      this.warning(_message, _source_1, _feature_1, _index_1, _code_1, _issueData);
    } else {
      boolean _and_3 = false;
      boolean _and_4 = false;
      EObject _source_2 = it.getSource();
      boolean _notEquals_4 = (!Objects.equal(_source_2, null));
      if (!_notEquals_4) {
        _and_4 = false;
      } else {
        EStructuralFeature _feature_2 = it.getFeature();
        boolean _notEquals_5 = (!Objects.equal(_feature_2, null));
        _and_4 = _notEquals_5;
      }
      if (!_and_4) {
        _and_3 = false;
      } else {
        String _code_2 = it.getCode();
        boolean _notEquals_6 = (!Objects.equal(_code_2, null));
        _and_3 = _notEquals_6;
      }
      if (_and_3) {
        String _message_1 = it.getMessage();
        EObject _source_3 = it.getSource();
        EStructuralFeature _feature_3 = it.getFeature();
        String _code_3 = it.getCode();
        String[] _issueData_1 = it.getIssueData();
        this.warning(_message_1, _source_3, _feature_3, _code_3, _issueData_1);
      } else {
        boolean _and_5 = false;
        boolean _and_6 = false;
        EObject _source_4 = it.getSource();
        boolean _notEquals_7 = (!Objects.equal(_source_4, null));
        if (!_notEquals_7) {
          _and_6 = false;
        } else {
          EStructuralFeature _feature_4 = it.getFeature();
          boolean _notEquals_8 = (!Objects.equal(_feature_4, null));
          _and_6 = _notEquals_8;
        }
        if (!_and_6) {
          _and_5 = false;
        } else {
          int _index_2 = it.getIndex();
          boolean _notEquals_9 = (_index_2 != (-1));
          _and_5 = _notEquals_9;
        }
        if (_and_5) {
          String _message_2 = it.getMessage();
          EObject _source_5 = it.getSource();
          EStructuralFeature _feature_5 = it.getFeature();
          int _index_3 = it.getIndex();
          this.warning(_message_2, _source_5, _feature_5, _index_3);
        } else {
          boolean _and_7 = false;
          EObject _source_6 = it.getSource();
          boolean _notEquals_10 = (!Objects.equal(_source_6, null));
          if (!_notEquals_10) {
            _and_7 = false;
          } else {
            EStructuralFeature _feature_6 = it.getFeature();
            boolean _notEquals_11 = (!Objects.equal(_feature_6, null));
            _and_7 = _notEquals_11;
          }
          if (_and_7) {
            String _message_3 = it.getMessage();
            EObject _source_7 = it.getSource();
            EStructuralFeature _feature_7 = it.getFeature();
            this.warning(_message_3, _source_7, _feature_7);
          } else {
            boolean _and_8 = false;
            boolean _and_9 = false;
            EStructuralFeature _feature_8 = it.getFeature();
            boolean _notEquals_12 = (!Objects.equal(_feature_8, null));
            if (!_notEquals_12) {
              _and_9 = false;
            } else {
              int _index_4 = it.getIndex();
              boolean _notEquals_13 = (_index_4 != (-1));
              _and_9 = _notEquals_13;
            }
            if (!_and_9) {
              _and_8 = false;
            } else {
              String _code_4 = it.getCode();
              boolean _notEquals_14 = (!Objects.equal(_code_4, null));
              _and_8 = _notEquals_14;
            }
            if (_and_8) {
              String _message_4 = it.getMessage();
              EStructuralFeature _feature_9 = it.getFeature();
              int _index_5 = it.getIndex();
              String _code_5 = it.getCode();
              String[] _issueData_2 = it.getIssueData();
              this.warning(_message_4, _feature_9, _index_5, _code_5, _issueData_2);
            } else {
              boolean _and_10 = false;
              EStructuralFeature _feature_10 = it.getFeature();
              boolean _notEquals_15 = (!Objects.equal(_feature_10, null));
              if (!_notEquals_15) {
                _and_10 = false;
              } else {
                String _code_6 = it.getCode();
                boolean _notEquals_16 = (!Objects.equal(_code_6, null));
                _and_10 = _notEquals_16;
              }
              if (_and_10) {
                String _message_5 = it.getMessage();
                EStructuralFeature _feature_11 = it.getFeature();
                String _code_7 = it.getCode();
                String[] _issueData_3 = it.getIssueData();
                this.warning(_message_5, _feature_11, _code_7, _issueData_3);
              } else {
                boolean _and_11 = false;
                EStructuralFeature _feature_12 = it.getFeature();
                boolean _notEquals_17 = (!Objects.equal(_feature_12, null));
                if (!_notEquals_17) {
                  _and_11 = false;
                } else {
                  int _index_6 = it.getIndex();
                  boolean _notEquals_18 = (_index_6 != (-1));
                  _and_11 = _notEquals_18;
                }
                if (_and_11) {
                  String _message_6 = it.getMessage();
                  EStructuralFeature _feature_13 = it.getFeature();
                  int _index_7 = it.getIndex();
                  this.warning(_message_6, _feature_13, _index_7);
                } else {
                  boolean _and_12 = false;
                  EObject _source_8 = it.getSource();
                  boolean _notEquals_19 = (!Objects.equal(_source_8, null));
                  if (!_notEquals_19) {
                    _and_12 = false;
                  } else {
                    EStructuralFeature _feature_14 = it.getFeature();
                    boolean _notEquals_20 = (!Objects.equal(_feature_14, null));
                    _and_12 = _notEquals_20;
                  }
                  if (_and_12) {
                    String _message_7 = it.getMessage();
                    EStructuralFeature _feature_15 = it.getFeature();
                    this.warning(_message_7, _feature_15);
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  
  private void runIssue(final ValidationIssue issue) {
    if (issue instanceof ValidationError) {
      _runIssue((ValidationError)issue);
      return;
    } else if (issue instanceof ValidationWarning) {
      _runIssue((ValidationWarning)issue);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(issue).toString());
    }
  }
}
