/*
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OntoLRuntimeModule extends AbstractOntoLRuntimeModule {
}
