/*
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol

import com.google.inject.Injector
import org.eclipse.emf.ecore.EPackage
import br.ufes.inf.nemo.ontol.model.ModelPackage

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OntoLStandaloneSetup extends OntoLStandaloneSetupGenerated {

	def static void doSetup() {
		new OntoLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
	
	override register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.nemo.inf.ufes.br/ontol/OntoL")) {
            EPackage.Registry.INSTANCE.put("http://www.nemo.inf.ufes.br/ontol/OntoL",ModelPackage.eINSTANCE);
        }
		
		super.register(injector)
	}
	
}
