/**
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol;

import br.ufes.inf.nemo.ontol.OntoLStandaloneSetupGenerated;
import br.ufes.inf.nemo.ontol.model.ModelPackage;
import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntoLStandaloneSetup extends OntoLStandaloneSetupGenerated {
  public static void doSetup() {
    OntoLStandaloneSetup _ontoLStandaloneSetup = new OntoLStandaloneSetup();
    _ontoLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey("http://www.nemo.inf.ufes.br/ontol/OntoL");
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put("http://www.nemo.inf.ufes.br/ontol/OntoL", ModelPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
