/**
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol;

import br.ufes.inf.nemo.ontol.AbstractOntoLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntoLRuntimeModule extends AbstractOntoLRuntimeModule {
}
