/*
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol.ui;

import br.ufes.inf.nemo.ontol.ui.internal.OntolActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OntoLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OntolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OntolActivator.getInstance().getInjector(OntolActivator.BR_UFES_INF_NEMO_ONTOL_ONTOL);
	}
	
}
