/*
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol.ide.contentassist.antlr;

import br.ufes.inf.nemo.ontol.ide.contentassist.antlr.internal.InternalOntoLParser;
import br.ufes.inf.nemo.ontol.services.OntoLGrammarAccess;
import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class OntoLParser extends AbstractContentAssistParser {

	@Inject
	private OntoLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalOntoLParser createParser() {
		InternalOntoLParser result = new InternalOntoLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getAlternatives_3(), "rule__Model__Alternatives_3");
					put(grammarAccess.getModelElementAccess().getAlternatives_0(), "rule__ModelElement__Alternatives_0");
					put(grammarAccess.getEntityDeclarationAccess().getAlternatives(), "rule__EntityDeclaration__Alternatives");
					put(grammarAccess.getIndividualAccess().getAlternatives_3_1(), "rule__Individual__Alternatives_3_1");
					put(grammarAccess.getOntoLClassAccess().getAlternatives_0(), "rule__OntoLClass__Alternatives_0");
					put(grammarAccess.getOntoLClassAccess().getAlternatives_1_1(), "rule__OntoLClass__Alternatives_1_1");
					put(grammarAccess.getOrderlessClassAccess().getAlternatives_6(), "rule__OrderlessClass__Alternatives_6");
					put(grammarAccess.getHOClassAccess().getAlternatives_7(), "rule__HOClass__Alternatives_7");
					put(grammarAccess.getELEMENTBOUNDAccess().getAlternatives(), "rule__ELEMENTBOUND__Alternatives");
					put(grammarAccess.getAttributeAssignmentAccess().getAlternatives_3(), "rule__AttributeAssignment__Alternatives_3");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getAlternatives_2(), "rule__SimpleAttributeAssignment__Alternatives_2");
					put(grammarAccess.getReferenceAssignmentAccess().getAlternatives_3(), "rule__ReferenceAssignment__Alternatives_3");
					put(grammarAccess.getDataValueAccess().getAlternatives(), "rule__DataValue__Alternatives");
					put(grammarAccess.getBOOLEANAccess().getAlternatives(), "rule__BOOLEAN__Alternatives");
					put(grammarAccess.getComplexDataValueAccess().getAlternatives(), "rule__ComplexDataValue__Alternatives");
					put(grammarAccess.getGeneralizationSetAccess().getAlternatives_0(), "rule__GeneralizationSet__Alternatives_0");
					put(grammarAccess.getCategorizationTypeAccess().getAlternatives(), "rule__CategorizationType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_3_0(), "rule__Model__Group_3_0__0");
					put(grammarAccess.getModelElementAccess().getGroup(), "rule__ModelElement__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getIndividualAccess().getGroup(), "rule__Individual__Group__0");
					put(grammarAccess.getIndividualAccess().getGroup_2(), "rule__Individual__Group_2__0");
					put(grammarAccess.getIndividualAccess().getGroup_2_2(), "rule__Individual__Group_2_2__0");
					put(grammarAccess.getIndividualAccess().getGroup_3(), "rule__Individual__Group_3__0");
					put(grammarAccess.getOntoLClassAccess().getGroup(), "rule__OntoLClass__Group__0");
					put(grammarAccess.getOntoLClassAccess().getGroup_1(), "rule__OntoLClass__Group_1__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup(), "rule__OrderlessClass__Group__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_3(), "rule__OrderlessClass__Group_3__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_3_2(), "rule__OrderlessClass__Group_3_2__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_4(), "rule__OrderlessClass__Group_4__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_4_2(), "rule__OrderlessClass__Group_4_2__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_5(), "rule__OrderlessClass__Group_5__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_5_2(), "rule__OrderlessClass__Group_5_2__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_6_0(), "rule__OrderlessClass__Group_6_0__0");
					put(grammarAccess.getOrderlessClassAccess().getGroup_6_1(), "rule__OrderlessClass__Group_6_1__0");
					put(grammarAccess.getFOClassAccess().getGroup(), "rule__FOClass__Group__0");
					put(grammarAccess.getFOClassAccess().getGroup_3(), "rule__FOClass__Group_3__0");
					put(grammarAccess.getFOClassAccess().getGroup_3_2(), "rule__FOClass__Group_3_2__0");
					put(grammarAccess.getFOClassAccess().getGroup_4(), "rule__FOClass__Group_4__0");
					put(grammarAccess.getFOClassAccess().getGroup_4_2(), "rule__FOClass__Group_4_2__0");
					put(grammarAccess.getHOClassAccess().getGroup(), "rule__HOClass__Group__0");
					put(grammarAccess.getHOClassAccess().getGroup_4(), "rule__HOClass__Group_4__0");
					put(grammarAccess.getHOClassAccess().getGroup_4_2(), "rule__HOClass__Group_4_2__0");
					put(grammarAccess.getHOClassAccess().getGroup_5(), "rule__HOClass__Group_5__0");
					put(grammarAccess.getHOClassAccess().getGroup_5_2(), "rule__HOClass__Group_5_2__0");
					put(grammarAccess.getHOClassAccess().getGroup_6(), "rule__HOClass__Group_6__0");
					put(grammarAccess.getHOClassAccess().getGroup_6_2(), "rule__HOClass__Group_6_2__0");
					put(grammarAccess.getHOClassAccess().getGroup_7_0(), "rule__HOClass__Group_7_0__0");
					put(grammarAccess.getHOClassAccess().getGroup_7_1(), "rule__HOClass__Group_7_1__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_3(), "rule__Attribute__Group_3__0");
					put(grammarAccess.getAttributeAccess().getGroup_5(), "rule__Attribute__Group_5__0");
					put(grammarAccess.getAttributeAccess().getGroup_5_2(), "rule__Attribute__Group_5_2__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup_3(), "rule__Reference__Group_3__0");
					put(grammarAccess.getReferenceAccess().getGroup_5(), "rule__Reference__Group_5__0");
					put(grammarAccess.getReferenceAccess().getGroup_5_2(), "rule__Reference__Group_5_2__0");
					put(grammarAccess.getReferenceAccess().getGroup_6(), "rule__Reference__Group_6__0");
					put(grammarAccess.getAttributeAssignmentAccess().getGroup(), "rule__AttributeAssignment__Group__0");
					put(grammarAccess.getAttributeAssignmentAccess().getGroup_3_1(), "rule__AttributeAssignment__Group_3_1__0");
					put(grammarAccess.getAttributeAssignmentAccess().getGroup_3_1_2(), "rule__AttributeAssignment__Group_3_1_2__0");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getGroup(), "rule__SimpleAttributeAssignment__Group__0");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getGroup_2_1(), "rule__SimpleAttributeAssignment__Group_2_1__0");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getGroup_2_1_2(), "rule__SimpleAttributeAssignment__Group_2_1_2__0");
					put(grammarAccess.getReferenceAssignmentAccess().getGroup(), "rule__ReferenceAssignment__Group__0");
					put(grammarAccess.getReferenceAssignmentAccess().getGroup_3_1(), "rule__ReferenceAssignment__Group_3_1__0");
					put(grammarAccess.getReferenceAssignmentAccess().getGroup_3_1_2(), "rule__ReferenceAssignment__Group_3_1_2__0");
					put(grammarAccess.getNUMBERAccess().getGroup(), "rule__NUMBER__Group__0");
					put(grammarAccess.getNUMBERAccess().getGroup_2(), "rule__NUMBER__Group_2__0");
					put(grammarAccess.getNoneValueAccess().getGroup(), "rule__NoneValue__Group__0");
					put(grammarAccess.getUnamedIndividualAccess().getGroup(), "rule__UnamedIndividual__Group__0");
					put(grammarAccess.getUnamedIndividualAccess().getGroup_2(), "rule__UnamedIndividual__Group_2__0");
					put(grammarAccess.getGeneralizationSetAccess().getGroup(), "rule__GeneralizationSet__Group__0");
					put(grammarAccess.getGeneralizationSetAccess().getGroup_0_2(), "rule__GeneralizationSet__Group_0_2__0");
					put(grammarAccess.getGeneralizationSetAccess().getGroup_0_3(), "rule__GeneralizationSet__Group_0_3__0");
					put(grammarAccess.getGeneralizationSetAccess().getGroup_5(), "rule__GeneralizationSet__Group_5__0");
					put(grammarAccess.getGeneralizationSetAccess().getGroup_8(), "rule__GeneralizationSet__Group_8__0");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getIncludesAssignment_3_0_1(), "rule__Model__IncludesAssignment_3_0_1");
					put(grammarAccess.getModelAccess().getElementsAssignment_3_1(), "rule__Model__ElementsAssignment_3_1");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getIndividualAccess().getNameAssignment_1(), "rule__Individual__NameAssignment_1");
					put(grammarAccess.getIndividualAccess().getInstantiatedClassesAssignment_2_1(), "rule__Individual__InstantiatedClassesAssignment_2_1");
					put(grammarAccess.getIndividualAccess().getInstantiatedClassesAssignment_2_2_1(), "rule__Individual__InstantiatedClassesAssignment_2_2_1");
					put(grammarAccess.getIndividualAccess().getAttAssignmentsAssignment_3_1_0(), "rule__Individual__AttAssignmentsAssignment_3_1_0");
					put(grammarAccess.getIndividualAccess().getRefAssignmentsAssignment_3_1_1(), "rule__Individual__RefAssignmentsAssignment_3_1_1");
					put(grammarAccess.getOntoLClassAccess().getAttributesAssignment_1_1_0(), "rule__OntoLClass__AttributesAssignment_1_1_0");
					put(grammarAccess.getOntoLClassAccess().getAttAssignmentsAssignment_1_1_1(), "rule__OntoLClass__AttAssignmentsAssignment_1_1_1");
					put(grammarAccess.getOntoLClassAccess().getReferencesAssignment_1_1_2(), "rule__OntoLClass__ReferencesAssignment_1_1_2");
					put(grammarAccess.getOntoLClassAccess().getRefAssignmentsAssignment_1_1_3(), "rule__OntoLClass__RefAssignmentsAssignment_1_1_3");
					put(grammarAccess.getOrderlessClassAccess().getNameAssignment_2(), "rule__OrderlessClass__NameAssignment_2");
					put(grammarAccess.getOrderlessClassAccess().getInstantiatedClassesAssignment_3_1(), "rule__OrderlessClass__InstantiatedClassesAssignment_3_1");
					put(grammarAccess.getOrderlessClassAccess().getInstantiatedClassesAssignment_3_2_1(), "rule__OrderlessClass__InstantiatedClassesAssignment_3_2_1");
					put(grammarAccess.getOrderlessClassAccess().getSuperClassesAssignment_4_1(), "rule__OrderlessClass__SuperClassesAssignment_4_1");
					put(grammarAccess.getOrderlessClassAccess().getSuperClassesAssignment_4_2_1(), "rule__OrderlessClass__SuperClassesAssignment_4_2_1");
					put(grammarAccess.getOrderlessClassAccess().getSubordinatorsAssignment_5_1(), "rule__OrderlessClass__SubordinatorsAssignment_5_1");
					put(grammarAccess.getOrderlessClassAccess().getSubordinatorsAssignment_5_2_1(), "rule__OrderlessClass__SubordinatorsAssignment_5_2_1");
					put(grammarAccess.getOrderlessClassAccess().getCategorizationTypeAssignment_6_0_0(), "rule__OrderlessClass__CategorizationTypeAssignment_6_0_0");
					put(grammarAccess.getOrderlessClassAccess().getBasetypeAssignment_6_0_1(), "rule__OrderlessClass__BasetypeAssignment_6_0_1");
					put(grammarAccess.getOrderlessClassAccess().getPowertypeOfAssignment_6_1_1(), "rule__OrderlessClass__PowertypeOfAssignment_6_1_1");
					put(grammarAccess.getFOClassAccess().getNameAssignment_2(), "rule__FOClass__NameAssignment_2");
					put(grammarAccess.getFOClassAccess().getInstantiatedClassesAssignment_3_1(), "rule__FOClass__InstantiatedClassesAssignment_3_1");
					put(grammarAccess.getFOClassAccess().getInstantiatedClassesAssignment_3_2_1(), "rule__FOClass__InstantiatedClassesAssignment_3_2_1");
					put(grammarAccess.getFOClassAccess().getSuperClassesAssignment_4_1(), "rule__FOClass__SuperClassesAssignment_4_1");
					put(grammarAccess.getFOClassAccess().getSuperClassesAssignment_4_2_1(), "rule__FOClass__SuperClassesAssignment_4_2_1");
					put(grammarAccess.getHOClassAccess().getOrderAssignment_1(), "rule__HOClass__OrderAssignment_1");
					put(grammarAccess.getHOClassAccess().getNameAssignment_3(), "rule__HOClass__NameAssignment_3");
					put(grammarAccess.getHOClassAccess().getInstantiatedClassesAssignment_4_1(), "rule__HOClass__InstantiatedClassesAssignment_4_1");
					put(grammarAccess.getHOClassAccess().getInstantiatedClassesAssignment_4_2_1(), "rule__HOClass__InstantiatedClassesAssignment_4_2_1");
					put(grammarAccess.getHOClassAccess().getSuperClassesAssignment_5_1(), "rule__HOClass__SuperClassesAssignment_5_1");
					put(grammarAccess.getHOClassAccess().getSuperClassesAssignment_5_2_1(), "rule__HOClass__SuperClassesAssignment_5_2_1");
					put(grammarAccess.getHOClassAccess().getSubordinatorsAssignment_6_1(), "rule__HOClass__SubordinatorsAssignment_6_1");
					put(grammarAccess.getHOClassAccess().getSubordinatorsAssignment_6_2_1(), "rule__HOClass__SubordinatorsAssignment_6_2_1");
					put(grammarAccess.getHOClassAccess().getCategorizationTypeAssignment_7_0_0(), "rule__HOClass__CategorizationTypeAssignment_7_0_0");
					put(grammarAccess.getHOClassAccess().getBasetypeAssignment_7_0_1(), "rule__HOClass__BasetypeAssignment_7_0_1");
					put(grammarAccess.getHOClassAccess().getPowertypeOfAssignment_7_1_1(), "rule__HOClass__PowertypeOfAssignment_7_1_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getLowerBoundAssignment_3_1(), "rule__Attribute__LowerBoundAssignment_3_1");
					put(grammarAccess.getAttributeAccess().getUpperBoundAssignment_3_3(), "rule__Attribute__UpperBoundAssignment_3_3");
					put(grammarAccess.getAttributeAccess().getPropertyClassAssignment_4(), "rule__Attribute__PropertyClassAssignment_4");
					put(grammarAccess.getAttributeAccess().getSubsetOfAssignment_5_1(), "rule__Attribute__SubsetOfAssignment_5_1");
					put(grammarAccess.getAttributeAccess().getSubsetOfAssignment_5_2_1(), "rule__Attribute__SubsetOfAssignment_5_2_1");
					put(grammarAccess.getReferenceAccess().getNameAssignment_1(), "rule__Reference__NameAssignment_1");
					put(grammarAccess.getReferenceAccess().getLowerBoundAssignment_3_1(), "rule__Reference__LowerBoundAssignment_3_1");
					put(grammarAccess.getReferenceAccess().getUpperBoundAssignment_3_3(), "rule__Reference__UpperBoundAssignment_3_3");
					put(grammarAccess.getReferenceAccess().getPropertyClassAssignment_4(), "rule__Reference__PropertyClassAssignment_4");
					put(grammarAccess.getReferenceAccess().getSubsetOfAssignment_5_1(), "rule__Reference__SubsetOfAssignment_5_1");
					put(grammarAccess.getReferenceAccess().getSubsetOfAssignment_5_2_1(), "rule__Reference__SubsetOfAssignment_5_2_1");
					put(grammarAccess.getReferenceAccess().getOppositeToAssignment_6_1(), "rule__Reference__OppositeToAssignment_6_1");
					put(grammarAccess.getAttributeAssignmentAccess().getAttributeAssignment_1(), "rule__AttributeAssignment__AttributeAssignment_1");
					put(grammarAccess.getAttributeAssignmentAccess().getAssignmentsAssignment_3_0(), "rule__AttributeAssignment__AssignmentsAssignment_3_0");
					put(grammarAccess.getAttributeAssignmentAccess().getAssignmentsAssignment_3_1_1(), "rule__AttributeAssignment__AssignmentsAssignment_3_1_1");
					put(grammarAccess.getAttributeAssignmentAccess().getAssignmentsAssignment_3_1_2_1(), "rule__AttributeAssignment__AssignmentsAssignment_3_1_2_1");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getAttributeAssignment_0(), "rule__SimpleAttributeAssignment__AttributeAssignment_0");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getAssignmentsAssignment_2_0(), "rule__SimpleAttributeAssignment__AssignmentsAssignment_2_0");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getAssignmentsAssignment_2_1_1(), "rule__SimpleAttributeAssignment__AssignmentsAssignment_2_1_1");
					put(grammarAccess.getSimpleAttributeAssignmentAccess().getAssignmentsAssignment_2_1_2_1(), "rule__SimpleAttributeAssignment__AssignmentsAssignment_2_1_2_1");
					put(grammarAccess.getReferenceAssignmentAccess().getReferenceAssignment_1(), "rule__ReferenceAssignment__ReferenceAssignment_1");
					put(grammarAccess.getReferenceAssignmentAccess().getAssignmentsAssignment_3_0(), "rule__ReferenceAssignment__AssignmentsAssignment_3_0");
					put(grammarAccess.getReferenceAssignmentAccess().getAssignmentsAssignment_3_1_1(), "rule__ReferenceAssignment__AssignmentsAssignment_3_1_1");
					put(grammarAccess.getReferenceAssignmentAccess().getAssignmentsAssignment_3_1_2_1(), "rule__ReferenceAssignment__AssignmentsAssignment_3_1_2_1");
					put(grammarAccess.getReferenceValueAccess().getValueAssignment(), "rule__ReferenceValue__ValueAssignment");
					put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
					put(grammarAccess.getNumberValueAccess().getValueAssignment(), "rule__NumberValue__ValueAssignment");
					put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
					put(grammarAccess.getComplexDataValueAccess().getValueAssignment_0(), "rule__ComplexDataValue__ValueAssignment_0");
					put(grammarAccess.getComplexDataValueAccess().getUnnamedValueAssignment_1(), "rule__ComplexDataValue__UnnamedValueAssignment_1");
					put(grammarAccess.getUnamedIndividualAccess().getAttAssignmentsAssignment_1(), "rule__UnamedIndividual__AttAssignmentsAssignment_1");
					put(grammarAccess.getUnamedIndividualAccess().getAttAssignmentsAssignment_2_1(), "rule__UnamedIndividual__AttAssignmentsAssignment_2_1");
					put(grammarAccess.getGeneralizationSetAccess().getIsDisjointAssignment_0_0(), "rule__GeneralizationSet__IsDisjointAssignment_0_0");
					put(grammarAccess.getGeneralizationSetAccess().getIsCompleteAssignment_0_1(), "rule__GeneralizationSet__IsCompleteAssignment_0_1");
					put(grammarAccess.getGeneralizationSetAccess().getIsDisjointAssignment_0_2_0(), "rule__GeneralizationSet__IsDisjointAssignment_0_2_0");
					put(grammarAccess.getGeneralizationSetAccess().getIsCompleteAssignment_0_2_1(), "rule__GeneralizationSet__IsCompleteAssignment_0_2_1");
					put(grammarAccess.getGeneralizationSetAccess().getIsCompleteAssignment_0_3_0(), "rule__GeneralizationSet__IsCompleteAssignment_0_3_0");
					put(grammarAccess.getGeneralizationSetAccess().getIsDisjointAssignment_0_3_1(), "rule__GeneralizationSet__IsDisjointAssignment_0_3_1");
					put(grammarAccess.getGeneralizationSetAccess().getNameAssignment_2(), "rule__GeneralizationSet__NameAssignment_2");
					put(grammarAccess.getGeneralizationSetAccess().getGeneralAssignment_4(), "rule__GeneralizationSet__GeneralAssignment_4");
					put(grammarAccess.getGeneralizationSetAccess().getCategorizerAssignment_5_1(), "rule__GeneralizationSet__CategorizerAssignment_5_1");
					put(grammarAccess.getGeneralizationSetAccess().getSpecificsAssignment_7(), "rule__GeneralizationSet__SpecificsAssignment_7");
					put(grammarAccess.getGeneralizationSetAccess().getSpecificsAssignment_8_1(), "rule__GeneralizationSet__SpecificsAssignment_8_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalOntoLParser typedParser = (InternalOntoLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public OntoLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OntoLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
