/*
 * generated by Xtext 2.9.1
 */
package br.ufes.inf.nemo.ontol.tests

import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(OntoLInjectorProvider)
class OntoLParsingTest{

//	@Inject	extension ParseHelper<Model>
//	@Inject extension ValidationTestHelper

}
