/*
 * generated by Xtext 2.9.1
 */
package br.ufes.inf.nemo.ontol.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOntoLScopeProvider extends DelegatingScopeProvider {
}
