/**
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ontol.scoping;

import br.ufes.inf.nemo.ontol.scoping.AbstractOntoLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class OntoLScopeProvider extends AbstractOntoLScopeProvider {
}
